version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gocritic
    - revive
    - unused

issues:
  exclude-use-default: false
